services:
  ros-vnc-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros-vnc-devcontainer
    image: ros-foxy-vnc:dev
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # network_mode: "host"
    ports:
      # - 7400-7500:7400-7500/udp
      - 8000:8000/tcp
      - 5901:5901/tcp
      - 7410:7410/tcp 
      - 51820:51820/udp
      # - 11811:11811/tcp
      # - 11811:11811/udp
  
    volumes:
      # Mount the parent directory (your project root) into the workspace
      - ..:/workspace:cached
    environment:
      - DISPLAY=:1
      # - ROS_DOMAIN_ID=10
      - ROS_DOMAIN_ID=10 # Changed to 0 for baseline testing
      # Tell all ROS nodes in this container to use the Jetson as the hub:
   
    # Overrides default command so things don't shut down after the process ends.
    # We start the VNC server and then put the container to sleep so VS Code can attach to it.
    # command: /bin/sh -c "vncserver :1 -geometry 1280x800 -depth 24 -localhost no && sleep infinity"